/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjpenjualan;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Restu
 */
public class LapPenjualan extends javax.swing.JFrame {
    Connection Con;
    ResultSet RsJual;
    Statement stm;
    String tgl1,tgl2;
    private Object[][] dataTable = null;
    private String[] header = {"No Jual","Tanggal","Nama Konsumen","Kode Barang","Nama Barang","Harga Satuan","Jumlah","Total"};
    DefaultTableModel tableModel = new DefaultTableModel(
      new Object [][] {},header);
   
   /**
     * Creates new form LapPenjualan
     */
    public LapPenjualan() {
        initComponents();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        dtAwal.setDateFormat(sdf);
        dtAkhir.setDateFormat(sdf);
        open_db();
    }
    private void open_db()
{
         try{
	//	KoneksiMysql kon= new KoneksiMysql("penjualan");
		KoneksiMysql kon = new KoneksiMysql ("localhost","root","","penjualan");
		Con = kon.getConnection();
		//System.out.println("Berhasil ");
        }catch (Exception e) {
		System.out.println("Error : "+e);
		}
}
    private void format_tanggal()
{
    String DATE_FORMAT = "yyyy-MM-dd";
//String DATE_FORMAT = "dd-MM-yyyy"; //Refer Java DOCS for formats
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat(DATE_FORMAT);
    Calendar c1 = Calendar.getInstance();
    int year=c1.get(Calendar.YEAR);
    int month=c1.get(Calendar.MONTH)+1;
    int day=c1.get(Calendar.DAY_OF_MONTH);
    //tgl1=sdf.format(txtTgl.getValue());
    tgl1=dtAwal.getText();
    tgl2=dtAkhir.getText();
    //tgl2=Integer.toString(year)+"-"+Integer.toString(month)+"-"+Integer.toString(day);
    System.out.println("Tanggal  : " + tgl1);
    System.out.println("Tanggal2 : " + tgl2);

}
    private void baca_data()
{
    try{
        tgl1=dtAwal.getText();
        tgl2=dtAkhir.getText();
            stm = Con.createStatement();
            RsJual = stm.executeQuery("select * from v_penjualan where date(tgl_jual)>=" +
          "date('"+ tgl1+"') and  date(tgl_jual)<=" + "date('"+ tgl2+"') order by tgl_jual desc");
                
            ResultSetMetaData meta = RsJual.getMetaData();
            int col = meta.getColumnCount();            
            int baris = 0;
            while(RsJual.next()) {
                baris = RsJual.getRow();
            }
            CustomFormat cf=new CustomFormat();
            dataTable = new Object[baris][col];
            int x = 0;
            RsJual.beforeFirst();
            while(RsJual.next()) {
                dataTable[x][0] = RsJual.getString("no_jual");
                dataTable[x][1] = RsJual.getDate("tgl_jual");
                dataTable[x][2] = RsJual.getString("nm_kons");
                dataTable[x][3] = RsJual.getString("kd_brg");
                dataTable[x][4] = RsJual.getString("nm_brg");
                dataTable[x][5] = cf.customFormat("###,###.##",RsJual.getDouble("harga_jual"));
                dataTable[x][6] = RsJual.getInt("jml_jual");
                dataTable[x][7] = RsJual.getDouble("totjual");
                x++;
            }
            tblLapJual.setModel(new DefaultTableModel(dataTable,header));        
            //aturTabel();
    }
    catch(SQLException e)
    {
        JOptionPane.showMessageDialog(null, e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLapJual = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmdCari = new javax.swing.JButton();
        dtAwal = new datechooser.beans.DateChooserCombo();
        dtAkhir = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblLapJual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Jual", "Tanggal", "Nama Konsumen", "Kode Barang", "Nama Barang", "Harga Satuan", "Jumlah", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblLapJual);

        jButton1.setText("Export");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tgl");

        jLabel2.setText("s/d");

        cmdCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prjpenjualan/search.256x256.jpg"))); // NOI18N
        cmdCari.setText("Cari");
        cmdCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdCariMouseClicked(evt);
            }
        });
        cmdCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCariActionPerformed(evt);
            }
        });

        dtAwal.setLocale(new java.util.Locale("id", "", ""));

        dtAkhir.setLocale(new java.util.Locale("id", "", ""));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dtAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdCari)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dtAkhir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(cmdCari)
                            .addComponent(dtAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCariActionPerformed
        // TODO add your handling code here:
        baca_data();
    }//GEN-LAST:event_cmdCariActionPerformed

    private void cmdCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdCariMouseClicked
        // TODO add your handling code here:
        baca_data();
    }//GEN-LAST:event_cmdCariMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
        ExportToExcel ex=new ExportToExcel(tblLapJual, new File("DataPenjualan.xls"));
        //exportToExcel(tblBrg, new File("DataBarang.xls"));
        JOptionPane.showMessageDialog(null, "Sukses Export data .....");
        }catch(Exception e)
        {JOptionPane.showMessageDialog(null, e);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LapPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LapPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LapPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LapPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LapPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCari;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dtAkhir;
    private datechooser.beans.DateChooserCombo dtAwal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLapJual;
    // End of variables declaration//GEN-END:variables
}
