package com.restu.prjpenjualan;
import java.sql.*;
import java.text.DecimalFormat;
import java.io.*;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import javax.swing.JOptionPane;
class JTextFieldLimit extends PlainDocument {
  private int limit;
  JTextFieldLimit(int limit) {
    super();
    this.limit = limit;
  }

  JTextFieldLimit(int limit, boolean upper) {
    super();
    this.limit = limit;
  }

  public void insertString(int offset, String str, AttributeSet attr) throws BadLocationException {
    if (str == null)
      return;

    if ((getLength() + str.length()) <= limit) {
      super.insertString(offset, str, attr);
    }
  }
}

/**
 *
 * @author  mrjj
 */

public class frmBarang extends javax.swing.JFrame {
    Connection Con;
    ResultSet RsBrg;
    Statement stm;
    
    Boolean ada = false;
    String sSatuan;
    Boolean edit=false;
    int row;
   private Object[][] dataTable = null;
   private String[] header = {"Kode","Nama Barang","Satuan","Harga Jual","Harga Beli","Stok","Stok Min"};
   public TableCellRenderer kanan = new RataKanan();
   public TableCellRenderer tengah = new RataTengah();
   /** Creates new form frmBarang */
    public frmBarang() {
        initComponents();
        open_db();
        baca_data();
        aktif(false);
        setTombol(true);
        if (RsBrg!=null)
        {
            row=0;
        }    
        aturTabel();
       // setField(row);
    }
private void aturTabel()
{
        tblBrg.getColumnModel().getColumn(3).setCellRenderer(kanan); 
        tblBrg.getColumnModel().getColumn(4).setCellRenderer(kanan); 
        tblBrg.getColumnModel().getColumn(5).setCellRenderer(kanan);
        tblBrg.getColumnModel().getColumn(6).setCellRenderer(kanan);
}
public String customFormat(String pattern, double value ) {
      DecimalFormat myFormatter = new DecimalFormat(pattern);
      String output = myFormatter.format(value);
      return output;
}      

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        cmbSatuan = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmdSimpan = new javax.swing.JButton();
        cmdKeluar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtHargaBeli = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBrg = new javax.swing.JTable();
        cmdTambah = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmdBatal = new javax.swing.JButton();
        cmdKoreksi = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtStokMin = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        cmdExport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Data Barang");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Kode Barang"); // NOI18N

        txtKode.setName("txtkode"); // NOI18N
        txtKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Barang"); // NOI18N

        txtNama.setName("txtnama"); // NOI18N

        cmbSatuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buah", "Box", "Lusin", "Biji", "Kg" }));
        cmbSatuan.setName("cmbSatuan"); // NOI18N
        cmbSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSatuanActionPerformed(evt);
            }
        });

        jLabel3.setText("Satuan"); // NOI18N

        cmdSimpan.setText("Simpan"); // NOI18N
        cmdSimpan.setName("cmdSimpan"); // NOI18N
        cmdSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdSimpanMouseClicked(evt);
            }
        });
        cmdSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanActionPerformed(evt);
            }
        });

        cmdKeluar.setText("Keluar"); // NOI18N
        cmdKeluar.setName("cmdKeluar"); // NOI18N
        cmdKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKeluarActionPerformed(evt);
            }
        });

        jLabel4.setText("Harga Jual"); // NOI18N

        jLabel5.setText("Harga Beli"); // NOI18N

        jLabel6.setText("Stok"); // NOI18N

        txtHarga.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHarga.setName("txtHarga"); // NOI18N

        txtHargaBeli.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHargaBeli.setName("txtHargaBeli"); // NOI18N

        txtStok.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtStok.setName("txtStok"); // NOI18N

        tblBrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Barang", "Satuan", "Harga Jual", "Harga Beli", "Stok", "Stok Min"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBrg.setName("tblBarang"); // NOI18N
        tblBrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBrgMouseClicked(evt);
            }
        });
        tblBrg.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tblBrgCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        tblBrg.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblBrgPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblBrg);

        cmdTambah.setText("Tambah"); // NOI18N
        cmdTambah.setName("cmdTambah"); // NOI18N
        cmdTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTambahActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Data Barang"); // NOI18N

        cmdBatal.setText("Batal"); // NOI18N
        cmdBatal.setName("cmdTambah"); // NOI18N
        cmdBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBatalActionPerformed(evt);
            }
        });

        cmdKoreksi.setText("Koreksi");
        cmdKoreksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdKoreksiActionPerformed(evt);
            }
        });

        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        jLabel8.setText("Stok Minimal"); // NOI18N

        txtStokMin.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtStokMin.setName("txtStokMin"); // NOI18N

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        cmdExport.setText("Export");
        cmdExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNext)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmdTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdSimpan)
                                .addGap(5, 5, 5)
                                .addComponent(cmdKoreksi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdBatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdKeluar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmdExport))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbSatuan, javax.swing.GroupLayout.Alignment.LEADING, 0, 84, Short.MAX_VALUE)
                                        .addComponent(txtStok, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHargaBeli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, Short.MAX_VALUE)
                                        .addComponent(txtStokMin, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 73, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(txtStokMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSimpan)
                    .addComponent(cmdTambah)
                    .addComponent(cmdKoreksi)
                    .addComponent(cmdBatal)
                    .addComponent(cmdKeluar)
                    .addComponent(cmdHapus)
                    .addComponent(cmdExport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext)
                .addGap(43, 43, 43))
        );

        setSize(new java.awt.Dimension(615, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void cmdKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKeluarActionPerformed
   // System.exit(0);
    dispose();
    // TODO add your handling code here:
}//GEN-LAST:event_cmdKeluarActionPerformed

private void cmdSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanActionPerformed
       
    // TODO add your handling code here:
   
}//GEN-LAST:event_cmdSimpanActionPerformed

private void cmdSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdSimpanMouseClicked
// TODO add your handling code here:
    String tKode=txtKode.getText();
    String tNama=txtNama.getText();
   
    double hrg=Double.parseDouble(txtHarga.getText());
    double hrgbeli=Double.parseDouble(txtHargaBeli.getText());
    int stk=Integer.parseInt(txtStok.getText());
    int stkMin=Integer.parseInt(txtStokMin.getText());
    try{
        if (edit==true)
        {
            stm.executeUpdate("update barang set nm_brg='"+tNama+"',satuan='"+sSatuan+"',harga_jual="+hrg+",stok="+stk+",stok_min="+stkMin+",harga_beli="+hrgbeli + " where kd_brg='" + tKode + "'");
        }else
        {
            stm.executeUpdate("INSERT into barang VALUES('"+tKode+"','"+tNama+"','"+sSatuan+"',"+hrg+","+hrgbeli+","+stk+","+stkMin+")");
        }
         tblBrg.setModel(new DefaultTableModel(dataTable,header));
        baca_data();
        aktif(false);
        setTombol(true);
    }catch(SQLException e) {
	//	System.out.println("Error : "+e);
       JOptionPane.showMessageDialog(null, e);
	}
}//GEN-LAST:event_cmdSimpanMouseClicked

private void cmbSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSatuanActionPerformed
// TODO add your handling code here:
    JComboBox cSatuan = (javax.swing.JComboBox)evt.getSource();

//Membaca Item Yang Terpilih — > String

    sSatuan = (String)cSatuan.getSelectedItem();
}//GEN-LAST:event_cmbSatuanActionPerformed

private void cmdTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTambahActionPerformed
    // TODO add your handling code here:
    edit=false;
    aktif(true);
    setTombol(false);
    kosong();//GEN-LAST:event_cmdTambahActionPerformed
}

private void tblBrgPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblBrgPropertyChange
 // TODO add your handling code here:
    txtNama.setText((String)tblBrg.getValueAt(0,1));
    cmbSatuan.setSelectedItem((String)tblBrg.getValueAt(0,2));
  //  String harga = Double.toString((Double)tblBrg.getValueAt(0,3));
  //  txtHarga.setText(harga);
  //  String stok=Integer.toString((Integer)tblBrg.getValueAt(0,4));
   // txtStok.setText(stok);
   // String stokmin=Integer.toString((Integer)tblBrg.getValueAt(0,5));
   // txtStokMin.setText(stokmin);
    txtKode.setText((String)tblBrg.getValueAt(tblBrg.getSelectedColumnCount(),tblBrg.getSelectedRowCount()));//GEN-LAST:event_tblBrgPropertyChange
  
}
private void tblBrgCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tblBrgCaretPositionChanged
// TODO add your handling code here:
  //   txtKode.setText((String)tblBrg.getValueAt(tblBrg.getSelectedColumnCount(),tblBrg.getSelectedRowCount()));
}//GEN-LAST:event_tblBrgCaretPositionChanged

private void cmdBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBatalActionPerformed
// TODO add your handling code here:
    //baca_data();
   // setField();
    aktif(false);
    setTombol(true);//GEN-LAST:event_cmdBatalActionPerformed
}
private void tblBrgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBrgMouseClicked
    int row=tblBrg.getSelectedRow();
    setField(row);
}//GEN-LAST:event_tblBrgMouseClicked

private void cmdKoreksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdKoreksiActionPerformed
    // TODO add your handling code here:
    edit=true;//GEN-LAST:event_cmdKoreksiActionPerformed
    aktif(true);
    setTombol(false);
    txtKode.setEditable(false);
    String str= new String(txtHarga.getText());
    txtHarga.setText(str.replace(",", ""));
    txtHarga.setText(str.replace(".", ""));
    //System.out.println("Harga : "+txtHarga.getText());
    String str1= new String(txtHargaBeli.getText());
    txtHargaBeli.setText(str1.replace(",", ""));
    txtHargaBeli.setText(str1.replace(".", ""));
    //System.out.println("Harga : "+txtHarga.getText());
}

private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
    // TODO add your handling code here:
    try{
        int psn=JOptionPane.showConfirmDialog(this, "Data ini Yakin dihapus ??", "Hapus Data",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (psn==0) {
            String sql="delete from barang where kd_brg='" + txtKode.getText() + "'";
            stm.executeUpdate(sql);
            baca_data();
        }    
    //setField();
    }
    catch(SQLException e)
    {
        JOptionPane.showMessageDialog(null, e);
    }
}//GEN-LAST:event_cmdHapusActionPerformed

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    // TODO add your handling code here:
  //  baca_data();
}//GEN-LAST:event_formWindowActivated

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    // TODO add your handling code here:
   // baca_data();
}//GEN-LAST:event_formWindowOpened

private void txtKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_txtKodeActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        try
  {  queryRecord();
        if (RsBrg!=null)
     {
        if (RsBrg.next())
        {
            baca_ketemu();
        }
        else
       {
          RsBrg = null;
       }
     }
  }catch(Exception ex){System.out.println(ex);}
    }//GEN-LAST:event_btnNextActionPerformed

   private void exportToExcel(JTable table, File file) {
        try{
            TableModel tableModel = table.getModel();
            FileWriter fOut = new FileWriter(file);
            for(int i = 0; i < tableModel.getColumnCount(); i++){
                fOut.write(tableModel.getColumnName(i)+"\t");
            }
            fOut.write("\n");
            for(int i = 0; i < tableModel.getRowCount(); i++){
                for(int j = 0; j < tableModel.getColumnCount(); j++){
                    fOut.write(tableModel.getValueAt(i, j).toString()+"\t");
                }
                fOut.write("\n");
            }
            fOut.close();
        } catch (Exception e){
            e.printStackTrace();
        }
    }
    private void cmdExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExportActionPerformed
        // TODO add your handling code here:
        try{
 //       ExportToExcel ex=new ExportToExcel(tblBrg, new File("DataBarang.xls"));
        //exportToExcel(tblBrg, new File("DataBarang.xls"));
        JOptionPane.showMessageDialog(null, "Sukses Export data .....");
        }catch(Exception e)
        {JOptionPane.showMessageDialog(null, e);
            
        }
        
    }//GEN-LAST:event_cmdExportActionPerformed

private void setField(int row)
{
    
   // int col=tblBrg.getSelectedColumn();
    txtKode.setText((String)tblBrg.getValueAt(row,0));
    txtNama.setText((String)tblBrg.getValueAt(row,1));
    cmbSatuan.setSelectedItem((String)tblBrg.getValueAt(row,2));
    //String harga = Double.toString((Double)tblBrg.getValueAt(row,3));
    String harga =(String)tblBrg.getValueAt(row,3);
    txtHarga.setText(harga);
    //String harga1 = Double.toString((Double)tblBrg.getValueAt(row,4));
    String harga1 =(String)tblBrg.getValueAt(row,4);
    txtHargaBeli.setText(harga1);
    String stok=Integer.toString((Integer)tblBrg.getValueAt(row,5));
    txtStok.setText(stok);
    String stokmin=Integer.toString((Integer)tblBrg.getValueAt(row,6));
    txtStokMin.setText(stokmin);
}

//    String str = (String) jTable1.getValueAt(1, 0);
private void open_db()
{
  try{
KoneksiMysql kon = new KoneksiMysql 
        ("localhost","root","","penjualan");
Con = kon.getConnection();
}
  catch (Exception e) {
 System.out.println("Error : "+e);
}
}
public void queryRecord()
{
	        
	        String query = "select * from barang order by kd_brg";
        try {
	            Statement stmt = Con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
	            RsBrg = stmt.executeQuery(query);
        }catch(Exception ex){System.out.println(ex);}
} 
private void baca_ketemu()
{  
     try
  {
    txtKode.setText(RsBrg.getString("kd_brg"));
    txtNama.setText(RsBrg.getString("nm_brg"));
    cmbSatuan.setSelectedItem(RsBrg.getString("satuan"));
    txtHarga.setText(Double.toString(RsBrg.getDouble("harga_jual")));
    txtHargaBeli.setText(Double.toString(RsBrg.getDouble("harga_beli")));
    txtStok.setText(Integer.toString(RsBrg.getInt("stok")));
    txtStokMin.setText(Integer.toString(RsBrg.getInt("stok_min")));
  }catch(Exception ex){System.out.println(ex);}              
}
private void baca_data() 
{
    try{
            stm = Con.createStatement();
            RsBrg = stm.executeQuery("select * from barang order by kd_brg");
                
            ResultSetMetaData meta = RsBrg.getMetaData();
            int col = meta.getColumnCount();            
            int baris = 0;
            while(RsBrg.next()) {
                baris = RsBrg.getRow();
            }
            
            dataTable = new Object[baris][col];
            int x = 0;
            RsBrg.beforeFirst();
            while(RsBrg.next()) {
                dataTable[x][0] = RsBrg.getString("kd_brg");
                dataTable[x][1] = RsBrg.getString("nm_brg");
                dataTable[x][2] = RsBrg.getString("satuan");
                dataTable[x][3] = customFormat("###,###.##",RsBrg.getDouble("harga_jual"));
                dataTable[x][4] = customFormat("###,###.##",RsBrg.getDouble("harga_beli"));
                dataTable[x][5] = RsBrg.getInt("stok");
                dataTable[x][6] = RsBrg.getInt("stok_min");
                x++;
            }
            tblBrg.setModel(new DefaultTableModel(dataTable,header));        
            aturTabel();
    }
    catch(SQLException e)
    {
       JOptionPane.showMessageDialog(null, e);
    }
}

private void kosong()
{
    txtKode.setText("");
    txtNama.setText("");
    txtHarga.setText("");
    txtHargaBeli.setText("");
    txtStok.setText("");
    txtStokMin.setText("");
    txtKode.setDocument(new JTextFieldLimit(6));
}

private void aktif(boolean x)
{
    txtKode.setEditable(x);
    txtNama.setEditable(x);
    //cmbSatuan.setEditable(x);
    cmbSatuan.setEnabled(x);
    txtHarga.setEditable(x);
    txtHargaBeli.setEditable(x);
    txtStok.setEditable(x);
    txtStokMin.setEditable(x);

}
private void setTombol(boolean t)
{
    cmdTambah.setEnabled(t);
    cmdKoreksi.setEnabled(t);
    cmdHapus.setEnabled(t);
    cmdSimpan.setEnabled(!t);
    cmdBatal.setEnabled(!t);
    cmdKeluar.setEnabled(t);
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBarang().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbSatuan;
    private javax.swing.JButton cmdBatal;
    private javax.swing.JButton cmdExport;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdKeluar;
    private javax.swing.JButton cmdKoreksi;
    private javax.swing.JButton cmdSimpan;
    private javax.swing.JButton cmdTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblBrg;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtStokMin;
    // End of variables declaration//GEN-END:variables
    
}
