/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmMenu.java
 *
 * Created on 09 Des 08, 11:53:47
 */

package com.restu.prjpenjualan;
//import ReportInNetbean.frmLaporanBarang;
//import ReportInNetbean.frmLaporanKonsumen;
import java.sql.*;
import javax.swing.*;
import javax.swing.JOptionPane;
//import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author mrjj
 */
public class FrmMenu extends javax.swing.JFrame {
Connection Con;
public String user_login;
    /** Creates new form FrmMenu */
    public FrmMenu() {
        initComponents();
        open_db();
        //frmLogin uL=new frmLogin();
        //txtUser.setText(uL.getUser());
        //System.out.println("User : " + uL.getUser());
    }
    public FrmMenu(String user_login) {
        initComponents();
        open_db();
        txtUser.setText(user_login);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnData = new javax.swing.JMenu();
        mnBarang = new javax.swing.JMenuItem();
        mnSupplier = new javax.swing.JMenuItem();
        mnKonsumen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        mnLogout = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenuItem();
        mnTransaksi = new javax.swing.JMenu();
        mnJual = new javax.swing.JMenuItem();
        mnPembelian = new javax.swing.JMenuItem();
        mnLaporan = new javax.swing.JMenu();
        mnLapBarang = new javax.swing.JMenuItem();
        mnLapKonsumen = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        mnLapJual = new javax.swing.JMenuItem();
        mnLapBeli = new javax.swing.JMenuItem();
        mnUtility = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SmartPos V. Java");
        setBackground(new java.awt.Color(102, 102, 255));
        setSize(new java.awt.Dimension(1024, 760));

        jLabel1.setText("User :");

        mnData.setText("Data Master");

        mnBarang.setText("Data Barang");
        mnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangActionPerformed1(evt);
            }
        });
        mnData.add(mnBarang);

        mnSupplier.setText("Data Supplier");
        mnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSupplierActionPerformed(evt);
            }
        });
        mnData.add(mnSupplier);

        mnKonsumen.setText("Data Konsumen");
        mnKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKonsumenActionPerformed(evt);
            }
        });
        mnData.add(mnKonsumen);
        mnData.add(jSeparator1);

        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        mnData.add(mnLogout);

        mnKeluar.setText("Keluar");
        mnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKeluarActionPerformed(evt);
            }
        });
        mnData.add(mnKeluar);

        jMenuBar1.add(mnData);

        mnTransaksi.setText("Transaksi");

        mnJual.setText("Penjualan Barang");
        mnJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnJualActionPerformed(evt);
            }
        });
        mnTransaksi.add(mnJual);

        mnPembelian.setText("Pembelian Barang");
        mnTransaksi.add(mnPembelian);

        jMenuBar1.add(mnTransaksi);

        mnLaporan.setText("Laporan");

        mnLapBarang.setText("Data Barang");
        mnLapBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapBarangActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLapBarang);

        mnLapKonsumen.setText("Data Konsumen");
        mnLapKonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapKonsumenActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLapKonsumen);
        mnLaporan.add(jSeparator2);

        mnLapJual.setText("Data Penjualan");
        mnLapJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLapJualActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLapJual);

        mnLapBeli.setText("Data Pembelian");
        mnLaporan.add(mnLapBeli);

        jMenuBar1.add(mnLaporan);

        mnUtility.setText("Utility");

        jMenuItem1.setText("BackUp");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnUtility.add(jMenuItem1);

        jMenuBar1.add(mnUtility);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(481, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 373, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(649, 452));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKeluarActionPerformed
        // TODO add your handling code here:
        int psn=JOptionPane.showConfirmDialog(this, "Yakin keluar", "Pesan",JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (psn==0) System.exit(0);
    }//GEN-LAST:event_mnKeluarActionPerformed

    private void mnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangActionPerformed
        // TODO add your handling code here:
        new frmBarang().setVisible(true);
    }//GEN-LAST:event_mnBarangActionPerformed

    private void mnJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnJualActionPerformed
        // TODO add your handling code here:
        new frmTransaksi().setVisible(true);
    }//GEN-LAST:event_mnJualActionPerformed

    private void mnLapBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapBarangActionPerformed
        // TODO add your handling code here:
      //  report rpt = new report("lbarang.jrxml", Con);
        //JasperViewer.viewReport("lap_brg.jrxml",Con);
//       new frmLaporanBarang().setVisible(true);
        
    }//GEN-LAST:event_mnLapBarangActionPerformed

    private void mnLapKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapKonsumenActionPerformed
        // TODO add your handling code here:
     //  report rpt=new report("lap_konsumen.jrxml", Con);
    //    new frmLaporanKonsumen().setVisible(true);
    }//GEN-LAST:event_mnLapKonsumenActionPerformed

    private void mnBarangActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangActionPerformed1
        // TODO add your handling code here:
        new frmBarang().setVisible(true);
    }//GEN-LAST:event_mnBarangActionPerformed1

    private void mnKonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKonsumenActionPerformed
        // TODO add your handlineg code here:
        new frmKonsumen().setVisible(true);
    }//GEN-LAST:event_mnKonsumenActionPerformed

    private void mnLapJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLapJualActionPerformed
        // TODO add your handling code here:
        new LapPenjualan().setVisible(true);
       // report rpt=new report("lap_penjualan.jrxml", Con);
    }//GEN-LAST:event_mnLapJualActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       // new frmBackup().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSupplierActionPerformed
        // TODO add your handling code here:
        new frmSupplier().setVisible(true);
    }//GEN-LAST:event_mnSupplierActionPerformed

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        // TODO add your handling code here:
        int psn=JOptionPane.showConfirmDialog(this, "Logout System ?", "Pesan",JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (psn==0) {
        dispose();
        new frmLogin().setVisible(true);
        }
    }//GEN-LAST:event_mnLogoutActionPerformed
private void open_db()
{
         try{
		KoneksiMysql kon= new KoneksiMysql("penjualan");
	//	KoneksiMysql kon = new KoneksiMysql ("192.168.10.250","ajib","","ajib");
		Con = kon.getConnection();
		//System.out.println("Berhasil ");
        }catch (Exception e) {
		System.out.println("Error : "+e);
		}
}
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenuItem mnBarang;
    private javax.swing.JMenu mnData;
    private javax.swing.JMenuItem mnJual;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenuItem mnKonsumen;
    private javax.swing.JMenuItem mnLapBarang;
    private javax.swing.JMenuItem mnLapBeli;
    private javax.swing.JMenuItem mnLapJual;
    private javax.swing.JMenuItem mnLapKonsumen;
    private javax.swing.JMenu mnLaporan;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenuItem mnPembelian;
    private javax.swing.JMenuItem mnSupplier;
    private javax.swing.JMenu mnTransaksi;
    private javax.swing.JMenu mnUtility;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

}
